# GitHub Repository metadata
url: vcl-reports-store-layout-template-file
description: This example stores a report layout (XML-based template) within a text file.  
tags: [vcl, reports, layout, file]
