//**********************************************************************//
//                                                                      //
//                  This auxiliary unit was generated by                //
//                 DevExpress Project Settings Manager.                 //
//                                                                      //
//  The dxSettings unit reflects the current project settings in        //
//  the source code of your project. Do not modify this file directly.  //
//                                                                      //
//  Use the DevExpress Project Settings dialog to configure all project //
//  settings related to DevExpress components. Select the following     //
//  item in the main menu of your RAD Studio IDE to invoke the dialog:  //
//                                                                      //
//            Project | DevExpress Settings for Your Project            //
//                                                                      //
//**********************************************************************//

#pragma hdrstop
#pragma package(smart_init)

#include "System.SysUtils.hpp"
#include "Vcl.Themes.hpp"
#include "cxLookAndFeels.hpp"
#include "dxSkinsCore.hpp"
#include "dxSkinsForm.hpp"
#include "dxSkinWXI.hpp"

#pragma link "System.SysUtils"
#pragma link "Vcl.Themes"
#pragma link "cxLookAndFeels"
#pragma link "dxSkinsCore"
#pragma link "dxSkinsForm"
#pragma link "dxSkinWXI"

TProcedure FPrevInitProc = nullptr;

void LoadAppearanceToRootLookAndFeel(TcxRootLookAndFeel* ARoot) {
  ARoot->Kind = lfUltraFlat;
  ARoot->NativeStyle = false;
  ARoot->ScrollbarMode = sbmDefault;
  ARoot->ScrollMode = scmDefault;
  ARoot->SkinName = "WXI";
  ARoot->RenderMode = rmDefault;
  ARoot->TouchMode = false;
  ARoot->FormCorners = fcDefault;
  ARoot->SkinPaletteName = "Default";
  ARoot->ShowFormShadow = bDefault;
  ARoot->UseSkins = true;
  ARoot->UseImageSet = TdxSkinImageSet::imsDefault;
  ARoot->UseSkinsInPopupMenus = true;
  ARoot->UseGlobalSkin = true;
}

void LoadAppearance() {
#if (__BCPLUSPLUS__ >= 0x0770)
  TStyleManager::ChangeChildFormSystemBorder = False;
#endif
  cxProjectSettingsAreOverriding = true;
  cxCanUseSkinsWithoutSkinController = true;
  TcxRootLookAndFeel* ARoot = TcxRootLookAndFeel::Instance;
  ARoot->BeginUpdate();
  try {
    LoadAppearanceToRootLookAndFeel(ARoot);
  }
  __finally {
    ARoot->EndUpdate();
  }
  TdxVisualRefinements::LightStyleMode = lsmOnlyBorders;
}

void Initialize() {
  if (FPrevInitProc)
    FPrevInitProc();
  LoadAppearance();
}

void initialization(void) {
  FPrevInitProc = reinterpret_cast<TProcedure>(InitProc);
  InitProc = reinterpret_cast<void*>(&Initialize);
}
#pragma startup initialization 200
